### ISSUE TITLE
Css

### ISSUE THREAD

**Issue by Smada-nailuj** [Phantasy146/Flip-Coin#29]
in the files the Second css doesn't appear
**To Reproduce**
1. Go to ''https://github.com/Phantasy146/Flip-Coin/tree/dev"
3. Scroll down to 'the files'

**Save With Bug**
N/A

**Expected behavior**
An additional CSS file 
**Screenshots**
![image](https://user-images.githubusercontent.com/47906536/53963377-31cb9b80-40bb-11e9-9f5b-05af89168e5f.png)

**Comment by Phantasy146** [comment]
What do you mean the second css?

**Comment by Smada-nailuj** [comment]
when I made Css for the subpages i made a css thing for them

**Comment by Smada-nailuj** [comment]
i have managed to restore the files and have made a pull request to merge them back in to dev
