### ISSUE TITLE
Hot Keys

### ISSUE THREAD

**Issue by Smada-nailuj** [Phantasy146/Flip-Coin#30]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when new players can't figure out the hotkeys 
**Describe the solution you'd like**
Flip Coin (f)
Buy Robot (r)
buy builder (b) 
ect
**Describe alternatives you've considered**
none
**Additional context**

**Comment by Phantasy146** [comment]
Would it work if it was put in the tooltip, which I am planning on adding next?

**Comment by Smada-nailuj** [comment]
yes

**Comment by Smada-nailuj** [comment]
though they may get annoying so some way for a options tab of something similar?

**Comment by Phantasy146** [comment]
They don't have to be in your face. Also it can be that you have to hover for a certain amount of time before it shows.

**Comment by Phantasy146** [comment]
added in tooltips
