### ISSUE TITLE
Number scale

### ISSUE THREAD

**Issue by Smada-nailuj** [Phantasy146/Flip-Coin#33]
**Is your feature request related to a problem? Please describe.**
I am frustrated with this unfamiliar and un-intuitive number system,
**Describe the solution you'd like**
a list of the notation things
**Describe alternatives you've considered**
change the notation
**Additional context**

**Comment by Phantasy146** [comment]
I can add scientific notation. Should be pretty easy.

**Comment by Phantasy146** [comment]
added scientific notation in latest commit
