### ISSUE TITLE
button for batteries move

### ISSUE THREAD

**Issue by Phantasy146** [Phantasy146/Flip-Coin#35]
**Describe the bug**
The button for buying batteries move up and down.

**To Reproduce**
Be able to buy batteries, and when something new unlocks the button moves.

**Expected behavior**
Button should stay in same spot

**Screenshots**
![image](https://user-images.githubusercontent.com/32680459/54073999-7f7f0a00-425b-11e9-838b-6c5885b2db25.png)
![image](https://user-images.githubusercontent.com/32680459/54074028-c10fb500-425b-11e9-96e6-0459af785593.png)

**Additional context**
According to Smada, you need a space for it not to move.

**Comment by Smada-nailuj** [comment]
it's true you do need a button, i'll leave this issue open for the hope that crowd sourcing the problem may help.

**Comment by Smada-nailuj** [comment]
^space not button

**Comment by Smada-nailuj** [comment]
this issue is covered by a more comprehensive issue, as such I am closing this issue for that reason.
