### ISSUE TITLE
new css branch not updated

### ISSUE THREAD

**Issue by Smada-nailuj** [Phantasy146/Flip-Coin#39]
**Describe the bug**
the spin off branch new css notation is gone from the footer

**To Reproduce**
1. download the new css branch
2. run it
3. Scroll down to the footer

**Save With Bug**
no need

**Expected behavior**
a way to switch notation

**Screenshots**
![image](https://user-images.githubusercontent.com/47906536/54242865-8f694900-44fc-11e9-9a75-6917eb532faa.png)

**Additional context**

**Comment by Phantasy146** [comment]
don't worry, any conflicts like that will be fixed in merge. just edit the things you need to edit

**Comment by Smada-nailuj** [comment]
i also need a version that wont freeze on me when i try to unlock everything, do you have a way to do that with the curent css?

**Comment by Phantasy146** [comment]
did you try reloading? tell me if that fixes it

**Comment by Smada-nailuj** [comment]
Does not fix the issue

**Comment by Phantasy146** [comment]
ill try something

**Comment by Smada-nailuj** [comment]
any update?

**Comment by Phantasy146** [comment]
here's what ill do: i'll make the edits in the css branch

**Comment by Phantasy146** [comment]
check new css branch, make sure it's what you want
